# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title: Rob Lang
tagline: "Freelance Software Engineer"
description: "Freelancer and Software Engineer. Doing a lot of event-driven, cloud-native things with containers and kubernetes ❤️"
url: https://bobrossthepainter.github.io/website/
baseurl: /
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-postcss

author:
  name: "Robert Lang"
  url: https://www.linkedin.com/in/robert-lang-26129614a/

paginate: 5

# postcss:
#   cache: false

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/bobrossthepainter/website
