source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "kramdown-parser-gfm", "~> 1.1"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "redcarpet" 
gem "jekyll-gist"
gem "pygments.rb"
gem "jekyll-postcss"
gem "webrick", "~> 1.7"
